[project]
name = "lsp"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.11, <=3.13"
keywords = ["Pipeline", "Numpy", "Microscopy", "ScanImage", "Suite2p", "tiff"]
license = {text = "BSD-3-Clause"}
dependencies = [
    "mbo_utilities"
]

[project.optional-dependencies]
gui = [
    "mbo_utilities[gui]"
] 
notebook = [
    "mbo_utilities[notebook]"
]
all = [
    "mbo_utilities[all]"
]

[dependency-groups]
dev = [
	"pytest>=7.4.4",
	"ruff>=0.6.1",
]
doc = [
	"docutils>=0.21.2",
	"myst-nb>=1.2.0",
	"sphinx>=8.1.3",
	"sphinx-autodoc2>=0.5.0",
	"sphinx-book-theme>=1.1.4",
	"sphinx-copybutton>=0.5.2",
	"sphinx-design>=0.6.1"
]

[tool.uv]
default-groups = "all"

[tool.uv.sources]
mbo_utilities = { git = "https://github.com/MillerBrainObservatory/mbo_utilities", branch = "master" }
# fastplotlib = { git = "https://github.com/fastplotlib/fastplotlib", branch = "main" }
# pygfx = { git = "https://github.com/pygfx/pygfx", branch = "main" }

# https://github.com/charliermarsh/ruff
[tool.ruff]
line-length = 88
src = ["lbm_suite2p_python"]
exclude = ["docs", "exclude", "demos", "scripts"] 

[tool.ruff.lint]
pydocstyle = { convention = "numpy" }
select = ["ALL"]
ignore = [
	"D401",   # First line should be in imperative mood (remove to opt in)
	"COM812", # Missing trailing comma (conflicts with ruff format)
	"ISC001", # Import sorting (conflicts with ruff format)
	"FIX002", # Fixable issue
	"DOC201", # TODO(manzt) enable in follow-up PR; no doc for return type.
	"FBT",    # TODO(manzt): enable in follow-up PR; require bool options to be keyword-only.
]

[tool.ruff.lint.per-file-ignores]
"docs/*.py" = ["D"] 

[tool.setuptools.exclude-package-data]
"*" = ["data/*"]

[tool.setuptools.packages.find]
where = ["."]
include = ["lbm_suite2p_python*"]

[tool.coverage.report]
exclude_lines = [
	"pragma: no cover",
	"if TYPE_CHECKING:",
	"@overload",
	"except ImportError",
	"\\.\\.\\.",
	"raise NotImplementedError()"
]

[tool.versioneer]
VCS = "git"
style = "pep440"
versionfile_source = "lbm_suite2p_python/_version.py"
versionfile_build = "lbm_suite2p_python/_version.py"
tag_prefix = ""
parentdir_prefix_version = "lbm_suite2p_python-"
requires-python = ">=3.13"
dependencies = []
