[build-system]
requires = ["setuptools>=61", "wheel", "versioneer[toml]==0.29"]
build-backend = "setuptools.build_meta"

[project]
name = "mbo_utilities"
description = "Various utilities for the Miller Brain Observatory"
readme = "README.md"
license = {text = "BSD-3-Clause"}
dynamic = ["version"]
requires-python = ">=3.10, <=3.13"
keywords = ["Microscopy", "ScanImage", "multiROI", "Tiff"]
dependencies = [
    "tifffile",
    "scikit-image",
    "matplotlib",
    "imageio[ffmpeg]",
    "ffmpeg-python",
    "PyWavelets",
    "dask",
    "zarr",
    "h5py",
    "tqdm",
    "fabric",
    "fastplotlib",
    "pygfx",
	"tqdm"
]

[project.optional-dependencies]
gui = [
	"imgui-bundle",
	"pyqt5==5.15.11",
	"pyqt5-qt5==5.15.2",
] 
notebook = [
	"jupyter_rfb>=0.5.1",
	"jupyterlab",
	"sidecar",
	"ipywidgets>=8.0.0,<9",
	"anywidget",
]
all = [
	"imgui-bundle",
	"jupyter_rfb>=0.5.1",
	"jupyterlab",
	"sidecar",
	"ipywidgets>=8.0.0,<9",
	"anywidget",
	"pyqt5==5.15.11",
	"pyqt5-qt5==5.15.2",
]

[tool.uv]
default-groups = "all"

[tool.uv.sources]
fastplotlib = { git = "https://github.com/fastplotlib/fastplotlib", branch = "main" }
mbo_utilities = { git = "https://github.com/MillerBrainObservatory/mbo_utilities", branch = "master" }
pygfx = { git = "https://github.com/pygfx/pygfx", branch = "main" }

# https://github.com/charliermarsh/ruff
[tool.ruff]
line-length = 88
src = ["lbm_suite2p_python"]
exclude = ["docs", "exclude", "demos", "scripts"] 

[tool.ruff.lint]
pydocstyle = { convention = "numpy" }
select = ["ALL"]
ignore = [
	"D401",   # First line should be in imperative mood (remove to opt in)
	"COM812", # Missing trailing comma (conflicts with ruff format)
	"ISC001", # Import sorting (conflicts with ruff format)
	"FIX002", # Fixable issue
	"DOC201", # TODO(manzt) enable in follow-up PR; no doc for return type.
	"FBT",    # TODO(manzt): enable in follow-up PR; require bool options to be keyword-only.
]

[tool.ruff.lint.per-file-ignores]
"docs/*.py" = ["D"] 

[tool.setuptools.exclude-package-data]
"*" = ["data/*"]

[tool.coverage.report]
exclude_lines = [
	"pragma: no cover",
	"if TYPE_CHECKING:",
	"@overload",
	"except ImportError",
	"\\.\\.\\.",
	"raise NotImplementedError()"
]

[project.scripts]
mbo = "mbo_utilities.__main__:main"
assemble = "mbo_utilities.assembly:main"

[project.urls]
homepage = "https://github.com/millerbrainobservatory/mbo_utilities"

[tool.setuptools.packages.find]
where = ["."]
include = ["mbo_utilities*"]


[tool.versioneer]
VCS = "git"
style = "pep440"
versionfile_source = "mbo_utilities/_version.py"
versionfile_build = "mbo_utilities/_version.py"
tag_prefix = "mbo-utilities-"
parentdir_prefix = "mbo-utilities-"
