name: Build and Deploy Docs

on: 
  # push:
  #   branches:
  #     - master
  #   tags:
  #     - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
  # pull_request:
  #   branches:
  #     - master
  workflow_dispatch:

jobs:
  docs:
    if: |
      github.event_name != 'push' ||
      contains(github.event.head_commit.message, 'doc:') ||
      contains(github.event.head_commit.message, 'docs:')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Miniforge3
        run: |
          wget -O Miniforge3.sh "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-$(uname -m).sh"
          bash Miniforge3.sh -b -p "$HOME/conda"
          echo "$HOME/conda/bin" >> $GITHUB_PATH
          echo "CONDA_BASE=$HOME/conda" >> $GITHUB_ENV

      - name: Install system deps
        run: sudo apt-get install -y git ffmpeg libegl1-mesa-dev libgl1-mesa-dri libxcb-xfixes0-dev mesa-vulkan-drivers xorg-dev

      - name: Install Windows OpenGL
        if: runner.os == 'Windows'
        run: |
          git clone --depth 1 https://www.github.com/pyvista/gl-ci-helpers.git
          powershell gl-ci-helpers/appveyor/install_opengl.ps1

      - name: Conda Install
        shell: bash

        run: |
          source "$CONDA_BASE/etc/profile.d/conda.sh"
          conda create -y -n lsp python=3.12.7
          conda activate lsp
          pip install -e .
          pip install -r docs/requirements.txt
          sphinx-build -b html docs/ docs/_build/html --keep-going


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          force_orphan: true
