name: Deploy Docs

on:
  push:
    branches: [master]
  pull_request:
    branches: [dev, master]
  workflow_dispatch:

jobs:
  docs:
    if: |
      github.event_name != 'push' ||
      contains(github.event.head_commit.message, 'doc') ||
      contains(github.event.head_commit.message, 'docs')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo 
        uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12.7"
          enable-cache: true

      - name: Sync and build docs
        run: |
          GIT_LFS_SKIP_SMUDGE=1 uv sync --all-extras
          GIT_LFS_SKIP_SMUDGE=1 uv run sphinx-build -b html docs docs/_build/html

      - name: Deploy docs
        if: github.repository == 'MillerBrainObservatory/mbo_utilities'
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          force_orphan: true
