name: Deploy Docs

on:
  push:
    branches: [master]
  pull_request:
    branches: [dev, master]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # - name: Install system dependencies
      #   run: |
      #     sudo apt-get update -y -qq
      #     sudo apt-get install --no-install-recommends -y \
      #       xorg-dev \
      #       libx11-dev \
      #       libxcb1-dev \
      #       libxcb-glx0-dev

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.10"
          enable-cache: true

      - name: Sync dependencies
        run: GIT_LFS_SKIP_SMUDGE=1 uv sync --docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          force_orphan: true
