name: Deploy Docs

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  docs:
    if: |
      github.event_name != 'pull_request' ||
      contains(github.event.pull_request.title, 'bump') ||
      contains(github.event.head_commit.message, 'bump')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"
          enable-cache: true

      - name: Sync and build docs
        run: |
          GIT_LFS_SKIP_SMUDGE=1 uv lock --upgrade --prerelease=allow
          GIT_LFS_SKIP_SMUDGE=1 uv sync --extra docs
          GIT_LFS_SKIP_SMUDGE=1 uv run sphinx-build -b html docs docs/_build/html

      - name: Deploy to GitHub Pages
        if: github.repository == 'MillerBrainObservatory/mbo_utilities'
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          force_orphan: true
