name: Deploy Docs

on:
  workflow_dispatch:

jobs:
  docs:
    if: |
      github.event_name != 'push' ||
      contains(github.event.head_commit.message, 'doc') ||
      contains(github.event.head_commit.message, 'docs')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo 
        uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12.9"
          enable-cache: true

      - name: Install dependencies
        run: uv sync --frozen --extra docs
        env:
          GIT_LFS_SKIP_SMUDGE: 1

      - name: Build documentation
        run: uv run sphinx-build -b html docs docs/_build/html
        env:
          PYTHONPATH: ${{ github.workspace }}
          GIT_LFS_SKIP_SMUDGE: 1

      - name: Deploy docs
        if: github.repository == 'MillerBrainObservatory/mbo_utilities'
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          force_orphan: true
