name: Format Code

on:
  pull_request:
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12.9"
          enable-cache: true

      - name: Format with ruff
        run: |
          uv tool install ruff
          uv tool run ruff format .
