name: Install and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [dev, master]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      # - name: Install llvmpipe and lavapipe for offscreen canvas
      #   if: ${{ matrix.os == 'ubuntu-latest' }}
      #   run: |
      #     sudo apt-get update -y -qq
      #     sudo apt-get install --no-install-recommends -y ffmpeg libegl1-mesa-dev libgl1-mesa-dri libxcb-xfixes0-dev mesa-vulkan-drivers xorg-dev
      - name: Install uv@latest
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      # - name: Test - python ${{ matrix.python-version }}
      #   run: uv run --frozen pytest
      - name: uv sync
        run: uv sync --all-extras --dev --active
      - name: uv run pytest
        run: uv run pytest tests
