name: UV Example

on:
  push:
    branches: [master]
  pull_request:
    branches: [dev, master]
  workflow_dispatch:

jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
      - uses: actions/checkout@v4

      - name: List Files
        runs: ls -la

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        # For example, using `pytest`
        run: uv run pytest tests
