name: UV Example

on:
  push:
    branches: [master]
  pull_request:
    branches: [dev, master]
  workflow_dispatch:

jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
    with:
      python-version: ${{ matrix.python-version }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: List Files
        run: ls -la

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest tests || true
